apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-trace-app
  namespace: trace
  labels:
    app: flask-trace-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-trace-app
  template:
    metadata:
      labels:
        app: flask-trace-app
    spec:
      containers:
      - name: flask-trace-app
        image: azgmktregistry.azurecr.io/trace_id:0.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
      tolerations:
      - operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: flask-trace-app-service
  namespace: trace
spec:
  selector:
    app: flask-trace-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: flask-trace-app
    app.kubernetes.io/name: flask-trace-app
    app.kubernetes.io/version: 0.0.1
  name: flask-trace-app
  namespace: trace
spec:
  ingressClassName: nginx
  rules:
  - host: trace-oi01.gmarket.com
    http:
      paths:
      - backend:
          service:
            name: flask-trace-app-service
            port:
              number: 8080
        path: /
        pathType: Prefix